name: FinderApp
options:
  bundleIdPrefix: com.scaleify
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: "16.0"

settings:
  SWIFT_VERSION: 5.0
  TARGETED_DEVICE_FAMILY: "1,2"
  IPHONEOS_DEPLOYMENT_TARGET: 16.0

targets:
  FinderApp:
    type: application
    platform: iOS
    sources:
      - path: FinderApp
        excludes:
          - "**/*.xcassets"
          - "**/*.plist"
    resources:
      - FinderApp/Assets.xcassets
      - path: FinderApp/Preview Content
        type: folder
    info:
      path: FinderApp/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.scaleify.finderapp
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ENABLE_PREVIEWS: true
      DEVELOPMENT_ASSET_PATHS: "FinderApp/Preview Content"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""

schemes:
  FinderApp:
    build:
      targets:
        FinderApp: all
    run:
      config: Debug
      debugEnabled: true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
